import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        tertiary: "#735c00",
        "primary-fixed": "#ffdbd1",
        surface: "#faf9f5",
        "surface-container-low": "#f4f4f0",
        "surface-bright": "#faf9f5",
        "on-tertiary-fixed-variant": "#574500",
        "error-container": "#ffdad6",
        "surface-tint": "#a73918",
        "outline-variant": "#dfc0b7",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        outline: "#8b716a",
        "inverse-on-surface": "#f2f1ed",
        "on-secondary-fixed-variant": "#394b3d",
        "tertiary-container": "#c7a84a",
        "on-background": "#1b1c1a",
        "on-secondary-fixed": "#0e1f13",
        "surface-container-high": "#e9e8e4",
        "secondary-fixed-dim": "#b7ccb9",
        "on-primary-fixed": "#3b0900",
        "on-surface-variant": "#58423c",
        "surface-dim": "#dbdad6",
        error: "#ba1a1a",
        "on-secondary-container": "#546758",
        "on-secondary": "#ffffff",
        "primary-container": "#c54f2c",
        background: "#faf9f5",
        secondary: "#506354",
        "tertiary-fixed": "#ffe089",
        "primary-fixed-dim": "#ffb5a0",
        "tertiary-fixed-dim": "#e4c363",
        "inverse-primary": "#ffb5a0",
        "secondary-fixed": "#d3e8d5",
        "inverse-surface": "#2f312e",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#862201",
        "on-surface": "#1b1c1a",
        primary: "#a43716",
        "surface-container": "#efeeea",
        "on-primary-container": "#fffbff",
        "secondary-container": "#d0e5d2",
        "surface-container-highest": "#e3e2df",
        "on-tertiary-container": "#4e3d00",
        "on-tertiary-fixed": "#241a00",
        "surface-variant": "#e3e2df",
      },
      fontFamily: {
        "heading": ["Literata", "serif"],
        "display-lg": ["Literata", "serif"],
        "headline-md": ["Literata", "serif"],
        "body": ["Karla", "sans-serif"],
        "label-caps": ["Karla", "sans-serif"],
        button: ["Karla", "sans-serif"],
        "body-lg": ["Karla", "sans-serif"],
        "body-md": ["Karla", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "1.3", fontWeight: "600" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        button: [
          "16px",
          { lineHeight: "1", fontWeight: "700" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", fontWeight: "400" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "1.5", fontWeight: "400" },
        ],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "container-max": "1200px",
        "stack-md": "16px",
        unit: "4px",
        gutter: "24px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "margin-mobile": "20px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      boxShadow: {
        whisper: "0 4px 12px rgba(45, 45, 45, 0.05)",
        "coin-bevel": "inset 0 1px 1px rgba(255,255,255,0.4), 0 1px 2px rgba(0,0,0,0.1)",
        "stamped": "inset 0 1px 1px rgba(0,0,0,0.1), 0 1px 2px rgba(0,0,0,0.1)",
      },
      keyframes: {
        "active-press": {
          "0%": { transform: "scale(1)" },
          "100%": { transform: "scale(0.98)" },
        },
      },
      animation: {
        "active-press": "active-press 0.1s ease-in-out",
      },
    },
  },
  plugins: [],
};

export default config;
